# Generated by Django 5.1.3 on 2024-11-30 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.UUID('688798b4-047e-4c15-ad5a-61ecd4f1e85f'), primary_key=True, serialize=False),
        ),
    ]
