# Generated by Django 5.1.3 on 2024-12-03 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.UUID('ff228ef7-7b22-478b-a13a-0d89ddaeef86'), primary_key=True, serialize=False),
        ),
    ]
